"""
Detect and drop events generated by the log-extractor agent itself.

The scheduled upload task creates predictable Security/Sysmon noise (PowerShell,
wevtutil export, curl upload, task registration). Filter at ingest before DB insert.
"""

from __future__ import annotations

from typing import Any

from config import AGENT_INGEST_CONFIG
from event_parsers.common import event_data_map, normalize_payload, payload_value


def _text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _lower(value: Any) -> str:
    return _text(value).lower()


def _command_line(payload: dict[str, Any], identity: dict[str, str]) -> str:
    data = event_data_map(payload)
    return _lower(
        identity.get("CommandLine")
        or payload_value(payload, "CommandLine")
        or data.get("CommandLine")
        or identity.get("commandLine")
        or payload_value(payload, "commandLine")
    )


def _process_path(payload: dict[str, Any], identity: dict[str, str], *keys: str) -> str:
    data = event_data_map(payload)
    for key in keys:
        value = identity.get(key) or payload_value(payload, key) or data.get(key)
        text = _lower(value)
        if text:
            return text
    return ""


def _matches_marker(text: str, markers: tuple[str, ...]) -> bool:
    lowered = text.lower()
    return any(marker.lower() in lowered for marker in markers if marker)


def is_agent_generated_event(
    log_id: int,
    native_event_id: int,
    record: dict[str, Any],
    parsed_details: dict[str, Any] | None = None,
) -> bool:
    config = AGENT_INGEST_CONFIG
    if not config.filter_enabled:
        return False

    parsed_details = parsed_details or {}
    identity = parsed_details.get("identity") or {}
    payload = normalize_payload(record)
    markers = config.task_name_markers

    if native_event_id in (4698, 4702):
        task_name = _text(identity.get("TaskName") or payload_value(payload, "TaskName"))
        if _matches_marker(task_name, markers):
            return True

    if log_id in (0, 999) and native_event_id == 4688:
        process_name = _process_path(payload, identity, "NewProcessName")
        command_line = _command_line(payload, identity)
        if process_name.endswith("\\curl.exe") and (
            "logs/upload" in command_line
            or "/api/logs/upload" in command_line
            or (" -f " in command_line and " -x post" in command_line.replace("-X", " -x "))
        ):
            return True
        if _matches_marker(command_line, config.script_markers):
            return True
        if process_name.endswith("\\wevtutil.exe") and "epl" in command_line and "security" in command_line:
            return True
        if process_name.endswith("\\powershell.exe") and _matches_marker(command_line, config.script_markers):
            return True

    if log_id in (1, 999) and native_event_id == 1:
        image = _process_path(payload, identity, "image", "Image")
        command_line = _command_line(payload, identity)
        if image.endswith("\\curl.exe") and "logs/upload" in command_line:
            return True
        if _matches_marker(command_line, config.script_markers):
            return True
        if image.endswith("\\wevtutil.exe") and "epl" in command_line:
            return True

    if log_id in (1, 999) and native_event_id == 3:
        image = _process_path(payload, identity, "image", "Image")
        if image.endswith("\\curl.exe"):
            return True

    return False
